apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-prometheus-resource
  namespace: argocd
spec:
  project: kafka-third-part-project
  source:
    repoURL: https://github.com/nightbobo/data_lab_gitops.git
    targetRevision: main
    path: strimzi-gitops/prometheus/install
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
