apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kafka-third-part-project
  namespace: argocd
spec:
  description: "Project to manage Kafka Connect resources via GitOps"
  sourceRepos:
    - https://github.com/nightbobo/data_lab_gitops.git
  destinations:
    - namespace: kafka-cluster
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"