apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: gitops-kafka-connect
 namespace: argocd
spec:
 project: kafka-third-part-project
 source:
   repoURL: https://github.com/nightbobo/data_lab_gitops.git
   targetRevision: main
   path: strimzi-gitops/connect
 destination:
   server: https://kubernetes.default.svc
   namespace: kafka-connect
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - CreateNamespace=true