apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  namespace: kafka-connect
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.8.0
          ports:
            - containerPort: 9081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka-cluster:9092"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: "_schemas"
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TRACE
              value: "true"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "$(POD_NAME).schema-registry.kafka-cluster.svc.cluster.local"
            - name: SCHEMA_REGISTRY_GROUP_ID
              value: "schema-registry-cluster"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:9081"
                #          command: [ "sh", "-c", "export SCHEMA_REGISTRY_LISTENERS=http://$POD_NAME.schema-registry.kafka-cluster.svc.cluster.local:9081 && /etc/confluent/docker/run" ]
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: kafka-cluster
spec:
  clusterIP: None  # Headless Service 설정
  ports:
    - port: 9081
      targetPort: 9081
  selector:
    app: schema-registry